database:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: root
  data: bungeecord
  uuid:
    use: mysql
    row-uuid: 'uuid'
    row-name: 'name'
    table: 'uuiddatabase'
forbidden-commands-on-mute:
- w
- m
- msg